### PR TITLE
add titles based on routes

### PR DESCRIPTION
**Pull request by udaycruise2903**
- [ ]  #8 Yet to refactor renderhead function with the title of index site(FP india) as top-level variable.

### CODE REVIEW

**Comment by srid** [comment]
@udaycruise2903 Nice; yes adding the `r` argument is the correct approach. Don't forget to merge `master` (let me know if you need help).

**Comment by srid** [comment]
Alternatively, you can re-create a new branch/PR by applying [8241b4e](https://github.com/fpindia/fpindia-site/pull/9/commits/8241b4ef09d3e9ce5273be49fda33b61819cc387) on top of it. That's probably easier.

**Comment by udaycruise2903** [comment]
> @udaycruise2903 Nice; yes adding the `r` argument is the correct approach. Don't forget to merge `master` (let me know if you need help).

_I will reach out to you, if there are any issues with merging master branch_

**Comment by srid** [comment]
This PR is out of date after #12

**Pull request closed without merging**
